# docker-compose.yml
version: "3.7"
services:
  neo4j:
    image: neo4j:3.5
    ports:
      - "7474:7474"
      - "7373:7373"
      - "7687:7687"
    environment:
      - NEO4J_AUTH=none

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    command: mongod --replSet neomongo
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongo mongo:27017/test --quiet
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 40s

  mongoClient:
    image: mongo
    volumes:
      - ./deployment_scripts:/deployment_scripts
    command:
      - /deployment_scripts/rs_init.sh
    depends_on:
      mongo:
        condition: service_healthy
    links:
      - mongo

  mongo_connector:
    build: ./mongo_connector
    depends_on:
      - mongoClient
      - mongo
    links:
      - mongo
      - neo4j
    environment:
      - MONGO_HOST=mongo
      - NEO4J_HOST=neo4j
