version: "3.7"
services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    # environment:
    #   MONGO_INITDB_ROOT_USERNAME: "${MONGO_USER}"
    #   MONGO_INITDB_ROOT_PASSWORD: "${MONGO_PASS}"
    ports:
      - "27017:27017"
    command: mongod
    restart: always

  bigchaindb:
    container_name: bigchaindb
    depends_on:
      - mongodb
      - tendermint
    build:
      context: bigchaindb
      dockerfile: Dockerfile-dev
    # volumes:
      # - ./bigchaindb:/usr/src/app/bigchaindb
      # - ./tests:/usr/src/app/tests
      # - ./docs:/usr/src/app/docs
      # - ./htmlcov:/usr/src/app/htmlcov
      # - ./setup.py:/usr/src/app/setup.py
      # - ./setup.cfg:/usr/src/app/setup.cfg
      # - ./pytest.ini:/usr/src/app/pytest.ini
      # - ./tox.ini:/usr/src/app/tox.ini
    environment:
      BIGCHAINDB_DATABASE_BACKEND: localmongodb
      BIGCHAINDB_DATABASE_HOST: mongodb
      BIGCHAINDB_DATABASE_PORT: 27017
      # BIGCHAINDB_DATABASE_LOGIN: "${MONGO_USER}"
      # BIGCHAINDB_DATABASE_PASSWORD: "${MONGO_PASS}"
      BIGCHAINDB_SERVER_BIND: 0.0.0.0:9984
      BIGCHAINDB_WSSERVER_HOST: 0.0.0.0
      BIGCHAINDB_WSSERVER_ADVERTISED_HOST: bigchaindb
      BIGCHAINDB_TENDERMINT_HOST: tendermint
      BIGCHAINDB_TENDERMINT_PORT: 26657
    ports:
      - "9984:9984"
      - "9985:9985"
      - "26658:26658"
    healthcheck:
      test:
        [
          "CMD",
          "bash",
          "-c",
          "curl http://bigchaindb:9984 && curl http://tendermint:26657/abci_query",
        ]
      interval: 3s
      timeout: 5s
      retries: 3
    command: ".ci/entrypoint.sh"
    restart: always
    
  tendermint:
    image: tendermint/tendermint:v0.31.5
    container_name: tendermint
    volumes:
      - tm_data:/tendermint
    entrypoint: ""
    ports:
      - "26656:26656"
      - "26657:26657"
    command: sh -c "tendermint init && tendermint node --consensus.create_empty_blocks=false --proxy_app=tcp://bigchaindb:26658"
    restart: always

  vault:
    container_name: vault
    image: "vault"
    env_file:
      - .env
    ports:
      - 8200:8200
    cap_add:
      - "IPC_LOCK"
    depends_on: 
      bigchaindb:
        condition: service_healthy
      neo4j:
        condition: service_healthy
    environment:
      VAULT_LOCAL_CONFIG: '{"backend" : {"file" : {"path" : "/vault/file"}}}'
    volumes:
      - ./vault/config:/vault/config
      - ./vault/policies:/vault/policies
      - ./vault/data:/vault/data

  neo4j:
    image: neo4j
    container_name: neo4j
    ports: 
        - "7474:7474"
        - "7373:7373"
        - "7687:7687"
    environment:
        - NEO4J_AUTH=none
    volumes:
      - neo4j_data:/data 
      - neo4j_logs:/logs 
      - neo4j_import:/var/lib/neo4j/import 
      - neo4j_plugins:/plugins 
    healthcheck:
        test: perl -MIO::Socket::INET -e 'exit(! defined( IO::Socket::INET->new("localhost:7687")))'

  server:
    container_name: rasa-server
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile
      target: chatbot
    volumes:
      - ./chatbot:/app
    ports:
      - 5005:5005
    depends_on:
      - action

      
  action:
    container_name: rasa-action-server
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile
      target: action
    ports:
      - "5055:5055"
#    volumes:
#      - ./actions:/app
 

  main:
    container_name: main
    env_file:
      - .env
    build:
      context: ./server
      dockerfile: Dockerfile
      target: app-backend
    volumes:
      - ./server:/app/server
    command: npm run deploy
    ports:
      - 5000:5000
    depends_on:
      - vault
      - server
 
  build_medicalgraph:
    env_file:
      - .env
    build:
      context: ./QA-engine/Knowledge-Base
      dockerfile: Dockerfile
    environment:
      NEO4J_URL: "neo4j"
    depends_on: 
      neo4j:
        condition: service_healthy
    

  # nginx:
  #   container_name: "nginx"
  #   restart: unless-stopped
  #   build:
  #     context: nginx
  #   ports:
  #     - 8443:8443
  #   depends_on:
  #     - server

 

volumes:
  tm_data: {}
  neo4j_data: {}
  neo4j_logs: {}
  neo4j_import: {}
  neo4j_plugins: {}
