version: "3.7"
services:
    neo4j:
        image: neo4j
        ports: 
            - "7474:7474"
            - "7373:7373"
            - "7687:7687"
        environment:
            - NEO4J_AUTH=none

    mongo:
        image: mongo
        ports:
            - "27017:27017"
