version: '3'
services:
  app:
    image: "app"      #  this is your container running the sdk server and your actions
    container_name: "app"
    expose:
      - "5055"
    depends_on:
      - rasa

  rasa:
    image: "rasa/rasa"
    container_name: "rasa"
    expose:
      - "5005"
    depends_on:
      - mongo

  mongo:
    image: "mongo:3.7-jessie"
    container_name: "mongo"
    expose:
      - "27017"
    volumes:
      - ./mongo:/data/db

  duckling:
    image: "rasa/duckling:latest"
    container_name: "duckling"
    expose:
      - "8000"
