
# This is a basic workflow to help you get started with Actions

name: Deploy complete setup

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
   push:
      tags:
         - '*'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
   # This workflow contains a single job called "build"
   build:
      # The type of runner that the job will run on
      runs-on: ubuntu-latest

      # Steps represent a sequence of tasks that will be executed as part of the job
      steps:
         # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
         - uses: actions/checkout@v2

         - name: Deploy bigchaindb
           uses: appleboy/ssh-action@master
           env:
              BIGCHAIN_ENV: ${{secrets.BIGCHAIN_ENV}}
           with:
              host: ${{ secrets.BIGCHAIN_HOST }}
              username: ${{ secrets.USER }}
              password: ${{ secrets.PASSWORD }}
              port: ${{ secrets.PORT }}
              envs: BIGCHAIN_ENV
              script: |
                 cd /root/vortex-mit2020
                 git pull https://${{ secrets.GIT_TOKEN }}:x-oauth-basic@github.com/ejson03/vortex-mit2020.git master
                 echo "$BIGCHAIN_ENV" > .env
                 docker system prune -a
                 docker container stop $(docker container ls -aq)
                 docker container rm $(docker container ls -aq)
                 docker image prune -a
                 docker-compose up --build -d vault

         - name: Deploy chatbot
         uses: appleboy/ssh-action@master
         env:
            CHATBOT_ENV: ${{secrets.CHATBOT_ENV}}
         with:
            host: ${{ secrets.CHATBOT_HOST }}
            username: ${{ secrets.USER }}
            password: ${{ secrets.PASSWORD }}
            port: ${{ secrets.PORT }}
            envs: CHATBOT_ENV
            script: |
               cd /root/vortex-mit2020
               git pull https://${{ secrets.GIT_TOKEN }}:x-oauth-basic@github.com/ejson03/vortex-mit2020.git master
               echo "$CHATBOT_ENV" > .env
               docker system prune -a
               docker container stop $(docker container ls -aq)
               docker container rm $(docker container ls -aq)
               docker image prune -a
               docker-compose up --build -d action
         
         - name: Deploy main web app
         uses: appleboy/ssh-action@master
         env:
            SERVER_ENV: ${{secrets.SERVER_ENV}}
         with:
            host: ${{ secrets.SERVER_HOST }}
            username: ${{ secrets.USER }}
            password: ${{ secrets.PASSWORD }}
            port: ${{ secrets.PORT }}
            envs: SERVER_ENV
            script: |
               cd /root/vortex-mit2020
               git pull https://${{ secrets.GIT_TOKEN }}:x-oauth-basic@github.com/ejson03/vortex-mit2020.git master
               echo "$SERVER_ENV" > .env
               docker system prune -a
               docker container stop $(docker container ls -aq)
               docker container rm $(docker container ls -aq)
               docker image prune -a
               docker-compose up --build -d main
