
# This is a basic workflow to help you get started with Actions

name: Deploy complete setup

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
   push:
      tags:
         - '*'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
   # This workflow contains a single job called "build"
   build:
      # The type of runner that the job will run on
      runs-on: ubuntu-latest

      # Steps represent a sequence of tasks that will be executed as part of the job
      steps:
         # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
         - uses: actions/checkout@v2

         - name: Deploy package to digitalocean
           uses: appleboy/ssh-action@master
           env:
              HOSTS: [${{secrets.ENV}}]
           with:
              host: ${{ secrets.HOST }}
              username: ${{ secrets.USERNAME }}
              password: ${{ secrets.PASSWORD }}
              port: ${{ secrets.PORT }}
              envs: FIREBASE_TOKEN
              script: |
                 cd /root/backend
                 git pull https://${{ secrets.GIT_TOKEN }}:x-oauth-basic@github.com/wadsworth-app/backend.git master
                 echo "$FIREBASE_TOKEN" > firebase.json
                 docker container stop server
                 docker container rm server
                 docker build -t "server" .
                 docker run --name server --network=wadsworth -d -t "server"
